name: rpc
version: 0.5.7-dev
author: Dart Team <misc@dartlang.org>
description: Library for exposing Dart server-side APIs.
homepage: https://github.com/dart-lang/rpc
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  collection: '>=1.1.1 <2.0.0'
  crypto: '>=1.0.0 <2.0.0'
  convert: '>=1.0.0 <2.0.0'
  discoveryapis_generator: '>=0.7.1+1 <0.8.0'
  gcloud: '>=0.2.0+12 <0.3.0'
  logging: '>=0.9.3 <0.12.0'
  path: '>=1.3.4 <2.0.0'
  uri: '>=0.9.3 <0.12.0'
  http_parser: '>=2.0.0 <3.0.0'
  mime: '>=0.9.3 <1.0.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
  test: '^0.12.4+7'
